### ISSUE TITLE
Statusline position

### ISSUE THREAD

**Issue by dtrckd** [drmad/tmux-git#13]
Hello, 

This tools overwrite the default statusline of tmux (on the right). Is there a way to chage this, by placong the git info in the middle of the status line, or by stacking it in the status line ?

**Comment by drmad** [comment]
Hi there,

Tmux have only two positions for the status line: left and right. You can change the location of the git status changing the `TMUX_STATUS_LOCATION` variable in `~/.tmux-git.conf`.

You can also change the info displayed by changing the `TMUX_STATUS` variable inside the `TMUX_STATUS_DEFINITION()` function, defined on the same file. 

E.g. if you want to stack your original status line, you can update `TMUX_STATUS` to something like:

    TMUX_STATUS="`tmux show -vg status-right` - $TMUX_STATUS"

**Comment by dtrckd** [comment]
Ok, thanks, for the answer.
