### ISSUE TITLE
readlink: illegal option -- e usage: readlink [-n] [file ...] when opening tmux

### ISSUE THREAD

**Issue by mihaineacsu** [drmad/tmux-git#4]
Running on OS X 10.10, it seems the FreeBSD's readlink has different available argument, *-e* not being one of them. Here's a link to OS X's readlink man page:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/readlink.1.html

Any thoughts on how to fix this?

**Comment by dmonopoly** [comment]
Has this been resolved?

**Comment by drmad** [comment]
Wow, It's been a long time for this issue :) Sorry, I doesn't have access nor time to test my script on a Mac. So yes @mihaineacsu , you pr is totally welcome :)

**Comment by jsan4christ** [comment]
greadlink was my life save, thanks for pointing that out.
