### ISSUE TITLE
.bashrc statement running tmux-git.sh even when no tmux session

### ISSUE THREAD

**Issue by michael-coleman** [drmad/tmux-git#7]
Hi,
this is a great script, thanks for sharing it!
I found I was gettting an error when I login to Ubuntu and also when I open a terminal when *tmux is not running*, something like

> error: tmux session not running

When I looked into it what I found that this statement that I put into `.bashrc`

    if [[ \$TMUX ]]; then source ~/.tmux-git/tmux-git.sh; fi

seems to run all the time, even if `$TMUX` is not set , because bash expands this test `[[ \$TMUX ]]` 
to `[[ -n "$TMUX" ]]` , and because the backslash escape causes `\$TMUX` to be a simple string, the test always returns true.  
I have replaced it with this code in my `.bashrc` and so far its running ok.

    if [[ -z ${TMUX+I_will_show_if_TMUX_is_set} ]]; then :; else source ~/.tmux-git/tmux-git.sh; fi

thought you might be interested to know.

**Comment by drmad** [comment]
Hi

Glad to hear you like the script :)  You should remove the slash before the $ in yout `.bashrc`. That slash is used only in the install process, because it's inside an `echo` command, so you can simply copy and paste the line.

**Comment by michael-coleman** [comment]
Oh right, I should have noticed that!  
Yes I did just copy the `if` statement directly and paste into `.bashrc` rather than run the command at a prompt, that's where the backslash came from.  
also,  when I run `tmux-git.sh` script the `repo branch` text isn't showing up on my tmux status bar very well, so Im currently reading through your script trying to work out how I can add some code to set the tmux options when `tmux-git.sh` runs, something like:

    set-option -g status-fg colour136 #yellow 
￼

**Comment by drmad** [comment]
That's a neat idea :smile: I'll look into it later. You can add your code to change tmux when inside a repo after the line 87, and after the line 107, `else` for the otherwise.
